/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vue;

import java.awt.Dimension;


/**
 *
 * @author Esteban
 */
public class FrmFenetrePrincipale extends javax.swing.JFrame {
    
    /**
     * Creates new form FrmFenetrePrincipale
     */
    public FrmFenetrePrincipale() {
        initComponents();
        Dimension tailleEcran = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        this.setBounds(0, 0, (int)tailleEcran.getWidth(), (int)tailleEcran.getHeight()-40);
        pnlCategorie1.setBounds(0, 40, this.getWidth()/2-10, this.getHeight()/2-35);
        pnlCategorie2.setBounds(this.getWidth()/2-5, 40, this.getWidth()/2-10, this.getHeight()/2-35);
        pnlCategorie3.setBounds(0, this.getHeight()/2-5, this.getWidth()/2-10, this.getHeight()/2-35);
        pnlCategorie4.setBounds(this.getWidth()/2-5, this.getHeight()/2-5, this.getWidth()/2-10, this.getHeight()/2-35);
        this.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlCategorie1 = new vue.PnlCategorie();
        pnlCategorie2 = new vue.PnlCategorie();
        pnlCategorie3 = new vue.PnlCategorie();
        pnlCategorie4 = new vue.PnlCategorie();
        pnlRecherche1 = new vue.PnlRecherche();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);
        getContentPane().add(pnlCategorie1);
        pnlCategorie1.setBounds(0, 50, 652, 329);
        getContentPane().add(pnlCategorie2);
        pnlCategorie2.setBounds(700, 50, 652, 329);
        getContentPane().add(pnlCategorie3);
        pnlCategorie3.setBounds(0, 390, 652, 329);
        getContentPane().add(pnlCategorie4);
        pnlCategorie4.setBounds(700, 390, 652, 329);
        getContentPane().add(pnlRecherche1);
        pnlRecherche1.setBounds(0, 0, 676, 30);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private vue.PnlCategorie pnlCategorie1;
    private vue.PnlCategorie pnlCategorie2;
    private vue.PnlCategorie pnlCategorie3;
    private vue.PnlCategorie pnlCategorie4;
    private vue.PnlRecherche pnlRecherche1;
    // End of variables declaration//GEN-END:variables

    public PnlCategorie getPnlCategorie1() {
        return pnlCategorie1;
    }

    public PnlCategorie getPnlCategorie2() {
        return pnlCategorie2;
    }

    public PnlCategorie getPnlCategorie3() {
        return pnlCategorie3;
    }

    public PnlCategorie getPnlCategorie4() {
        return pnlCategorie4;
    }

    
}
