/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vue;

import java.awt.Dimension;
import javax.swing.JFrame;

/**
 *
 * @author Esteban
 */
public class FrmGestionSite extends javax.swing.JFrame {

    /**
     * Creates new form FrmGestionSite
     */
    public FrmGestionSite() {
        initComponents();
        Dimension tailleEcran = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        this.setBounds(0, 0, (int)tailleEcran.getWidth(), (int)(tailleEcran.getHeight()/2));
        this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        pnlAjoutSite1.setBounds(0, 0, this.getWidth()/3, this.getHeight());
        pnlSupprimerSite1.setBounds(this.getWidth()/3, 0, this.getWidth()/3, this.getHeight());
        pnlFavories1.setBounds(2*this.getWidth()/3, 0, this.getWidth()/3, this.getHeight());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlAjoutSite1 = new vue.PnlAjoutSite();
        pnlSupprimerSite1 = new PnlSupprimerSite();
        pnlFavories1 = new vue.pnlFavories();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);
        getContentPane().add(pnlAjoutSite1);
        pnlAjoutSite1.setBounds(0, 0, 360, 310);
        getContentPane().add(pnlSupprimerSite1);
        pnlSupprimerSite1.setBounds(360, 0, 380, 310);
        getContentPane().add(pnlFavories1);
        pnlFavories1.setBounds(740, 0, 350, 320);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private vue.PnlAjoutSite pnlAjoutSite1;
    private vue.pnlFavories pnlFavories1;
    private vue.PnlSupprimerSite pnlSupprimerSite1;
    // End of variables declaration//GEN-END:variables
}
