/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vue;

/**
 *
 * @author Esteban
 */
public class PnlAjoutSite extends javax.swing.JPanel {

    /**
     * Creates new form PnlAjoutSite
     */
    public PnlAjoutSite() {
        initComponents();
        this.setBounds(0, 0, 240, 250);
        placeComposant();
    }
    
    public final void placeComposant(){
        lblAjouterSite.setBounds(0, this.getHeight()/10, this.getWidth(), this.getHeight()/6);
        lblTitreSite.setBounds(this.getWidth()/4, this.getHeight()/10+this.getHeight()/6+10, this.getWidth()/3, this.getHeight()/6);
        lblURL.setBounds(this.getWidth()/4, this.getHeight()/10+2*this.getHeight()/6+20, this.getWidth()/3, this.getHeight()/6);
        lblRSS.setBounds(this.getWidth()/4, this.getHeight()/10+3*this.getHeight()/6+30, this.getWidth()/3, this.getHeight()/6);
        lblCategorie.setBounds(this.getWidth()/4, this.getHeight()/10+4*this.getHeight()/6+40, this.getWidth()/3, this.getHeight()/6);
        txtTitreSite.setBounds(3*this.getWidth()/4, this.getHeight()/10+this.getHeight()/6+10, 4*this.getWidth()/5, this.getHeight()/7);
        txtUrl.setBounds(3*this.getWidth()/4, this.getHeight()/10+2*this.getHeight()/6+20, 4*this.getWidth()/5, this.getHeight()/7);
        txtRss.setBounds(3*this.getWidth()/4, this.getHeight()/10+3*this.getHeight()/6+30, 4*this.getWidth()/5, this.getHeight()/7);
        CmbBoxCategorie.setBounds(3*this.getWidth()/4, this.getHeight()/10+4*this.getHeight()/6+40, 4*this.getWidth()/5, this.getHeight()/7);
        btnAjouter.setBounds(this.getWidth()/3, this.getHeight()/10+5*this.getHeight()/6+50, 4*this.getWidth()/5, this.getHeight()/7);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitreSite = new javax.swing.JLabel();
        txtTitreSite = new javax.swing.JTextField();
        lblURL = new javax.swing.JLabel();
        txtUrl = new javax.swing.JTextField();
        lblRSS = new javax.swing.JLabel();
        txtRss = new javax.swing.JTextField();
        btnAjouter = new javax.swing.JButton();
        lblCategorie = new javax.swing.JLabel();
        CmbBoxCategorie = new javax.swing.JComboBox();
        lblAjouterSite = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createEtchedBorder());
        setLayout(null);

        lblTitreSite.setText("Nom du site");
        add(lblTitreSite);
        lblTitreSite.setBounds(20, 30, 130, 40);
        add(txtTitreSite);
        txtTitreSite.setBounds(170, 40, 150, 20);

        lblURL.setText("URL du site");
        add(lblURL);
        lblURL.setBounds(20, 90, 110, 40);
        add(txtUrl);
        txtUrl.setBounds(170, 100, 150, 20);

        lblRSS.setText("Flux RSS");
        add(lblRSS);
        lblRSS.setBounds(20, 150, 140, 30);
        add(txtRss);
        txtRss.setBounds(170, 150, 150, 20);

        btnAjouter.setText("Ajouter");
        add(btnAjouter);
        btnAjouter.setBounds(130, 260, 100, 23);

        lblCategorie.setText("Catégorie");
        add(lblCategorie);
        lblCategorie.setBounds(20, 200, 110, 40);

        CmbBoxCategorie.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(CmbBoxCategorie);
        CmbBoxCategorie.setBounds(170, 210, 150, 20);

        lblAjouterSite.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAjouterSite.setText("Ajouter un site");
        add(lblAjouterSite);
        lblAjouterSite.setBounds(110, 10, 170, 20);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox CmbBoxCategorie;
    private javax.swing.JButton btnAjouter;
    private javax.swing.JLabel lblAjouterSite;
    private javax.swing.JLabel lblCategorie;
    private javax.swing.JLabel lblRSS;
    private javax.swing.JLabel lblTitreSite;
    private javax.swing.JLabel lblURL;
    private javax.swing.JTextField txtRss;
    private javax.swing.JTextField txtTitreSite;
    private javax.swing.JTextField txtUrl;
    // End of variables declaration//GEN-END:variables
}
