/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vue;

/**
 *
 * @author Esteban
 */
public class pnlFavories extends javax.swing.JPanel {

    /**
     * Creates new form pnlFavories
     */
    public pnlFavories() {
        initComponents();
        this.setBounds(0, 0, 240, 250);
        placeComposant();
    }

    public void placeComposant(){
        lblCategoriesFavorites.setBounds(0, this.getHeight()/10, this.getWidth(), this.getHeight()/6);
        lblFavorie1.setBounds(this.getWidth()/4, this.getHeight()/10+this.getHeight()/6+10, this.getWidth()/3, this.getHeight()/6);
        lblFavorie2.setBounds(this.getWidth()/4, this.getHeight()/10+2*this.getHeight()/6+20, this.getWidth()/3, this.getHeight()/6);
        lblFavorie3.setBounds(this.getWidth()/4, this.getHeight()/10+3*this.getHeight()/6+30, this.getWidth()/3, this.getHeight()/6);
        lblFavorie4.setBounds(this.getWidth()/4, this.getHeight()/10+4*this.getHeight()/6+40, this.getWidth()/3, this.getHeight()/6);
        cmbBoxFav1.setBounds(3*this.getWidth()/4, this.getHeight()/10+this.getHeight()/6+10, 4*this.getWidth()/5, this.getHeight()/7);
        cmbBoxFav2.setBounds(3*this.getWidth()/4, this.getHeight()/10+2*this.getHeight()/6+20, 4*this.getWidth()/5, this.getHeight()/7);
        cmbBoxFav3.setBounds(3*this.getWidth()/4, this.getHeight()/10+3*this.getHeight()/6+30, 4*this.getWidth()/5, this.getHeight()/7);
        cmbBoxFav4.setBounds(3*this.getWidth()/4, this.getHeight()/10+4*this.getHeight()/6+40, 4*this.getWidth()/5, this.getHeight()/7);
        btnSauveFav.setBounds(this.getWidth()/3, this.getHeight()/10+5*this.getHeight()/6+50, 4*this.getWidth()/5, this.getHeight()/7);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblCategoriesFavorites = new javax.swing.JLabel();
        lblFavorie1 = new javax.swing.JLabel();
        lblFavorie2 = new javax.swing.JLabel();
        lblFavorie3 = new javax.swing.JLabel();
        lblFavorie4 = new javax.swing.JLabel();
        cmbBoxFav1 = new javax.swing.JComboBox();
        cmbBoxFav2 = new javax.swing.JComboBox();
        cmbBoxFav3 = new javax.swing.JComboBox();
        cmbBoxFav4 = new javax.swing.JComboBox();
        btnSauveFav = new javax.swing.JButton();

        setLayout(null);

        lblCategoriesFavorites.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCategoriesFavorites.setText("Catégories favorites");
        add(lblCategoriesFavorites);
        lblCategoriesFavorites.setBounds(0, 4, 400, 20);

        lblFavorie1.setText("Favorie 1");
        add(lblFavorie1);
        lblFavorie1.setBounds(20, 50, 120, 20);

        lblFavorie2.setText("Favorie 2");
        add(lblFavorie2);
        lblFavorie2.setBounds(20, 100, 110, 30);

        lblFavorie3.setText("Favorie 3");
        add(lblFavorie3);
        lblFavorie3.setBounds(20, 170, 110, 30);

        lblFavorie4.setText("Favorie 4");
        add(lblFavorie4);
        lblFavorie4.setBounds(20, 220, 90, 20);

        cmbBoxFav1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(cmbBoxFav1);
        cmbBoxFav1.setBounds(210, 50, 120, 20);

        cmbBoxFav2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(cmbBoxFav2);
        cmbBoxFav2.setBounds(210, 110, 120, 20);

        cmbBoxFav3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(cmbBoxFav3);
        cmbBoxFav3.setBounds(210, 170, 120, 20);

        cmbBoxFav4.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(cmbBoxFav4);
        cmbBoxFav4.setBounds(210, 220, 120, 20);

        btnSauveFav.setText("Confirmer");
        add(btnSauveFav);
        btnSauveFav.setBounds(100, 250, 120, 23);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSauveFav;
    private javax.swing.JComboBox cmbBoxFav1;
    private javax.swing.JComboBox cmbBoxFav2;
    private javax.swing.JComboBox cmbBoxFav3;
    private javax.swing.JComboBox cmbBoxFav4;
    private javax.swing.JLabel lblCategoriesFavorites;
    private javax.swing.JLabel lblFavorie1;
    private javax.swing.JLabel lblFavorie2;
    private javax.swing.JLabel lblFavorie3;
    private javax.swing.JLabel lblFavorie4;
    // End of variables declaration//GEN-END:variables
}
