/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vue;

import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.JLabel;

/**
 *
 * @author Esteban
 */
public class PnlNews extends javax.swing.JPanel {

    /**
     * Creates new form PnlNews
     */
    public PnlNews() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitreNews = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(null);

        lblTitreNews.setBackground(new java.awt.Color(255, 153, 51));
        lblTitreNews.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitreNews.setText("Titre de la news");
        lblTitreNews.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        add(lblTitreNews);
        lblTitreNews.setBounds(0, 0, 220, 150);
    }// </editor-fold>//GEN-END:initComponents

    public JLabel getLblTitreNews() {
        return lblTitreNews;
    }

    public void setLblTitreNews(JLabel lblTitreNews) {
        this.lblTitreNews = lblTitreNews;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblTitreNews;
    // End of variables declaration//GEN-END:variables
}
