/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vue;

import javax.swing.JButton;
import javax.swing.JTextField;

/**
 *
 * @author Esteban
 */
public class PnlRecherche extends javax.swing.JPanel {
    
    /**
     * Creates new form PnlRecherche
     */
    public PnlRecherche() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TxtRecherche = new javax.swing.JTextField();
        BtnRecherche = new javax.swing.JButton();
        BtnGestionSite = new javax.swing.JButton();

        TxtRecherche.setText("Rechercher une categorie ou un site");

        BtnRecherche.setText("Rechercher");

        BtnGestionSite.setText("Gestion des sites");
        BtnGestionSite.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BtnGestionSiteMousePressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TxtRecherche, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BtnRecherche, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                .addComponent(BtnGestionSite, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(BtnGestionSite)
                .addComponent(BtnRecherche)
                .addComponent(TxtRecherche, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void BtnGestionSiteMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnGestionSiteMousePressed
        FrmGestionSite fen = new FrmGestionSite();
        fen.setVisible(true);
    }//GEN-LAST:event_BtnGestionSiteMousePressed

    public JButton getBtnGestionSite() {
        return BtnGestionSite;
    }

    public JButton getBtnRecherche() {
        return BtnRecherche;
    }

    public JTextField getTxtRecherche() {
        return TxtRecherche;
    }

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnGestionSite;
    private javax.swing.JButton BtnRecherche;
    private javax.swing.JTextField TxtRecherche;
    // End of variables declaration//GEN-END:variables
}
