/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vue;

import javax.swing.JLabel;

/**
 *
 * @author Esteban
 */
public class PnlSite extends javax.swing.JPanel {

    /**
     * Creates new form PnlSite
     */
    public PnlSite() {
        initComponents();
        this.setSize(665, 190);
        lblNomSite.setBounds(5, 5, 200, 20);
        lblNomSite.setText("Nom du site!");
        pnlNews1.setBounds(5, 30, (int)this.getWidth()/3-10, 140);
        pnlNews2.setBounds((int)this.getWidth()/3, 30, (int)this.getWidth()/3-10, 140);
        pnlNews3.setBounds((int)(this.getWidth()/3)*2-5, 30, (int)this.getWidth()/3-10, 140);
        
        /*pnlNews1.setBounds(5, 5, 220, 140);
        pnlNews2.setBounds(230, 5, 220, 140);
        pnlNews3.setBounds(460, 5, 220, 140);*/
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNomSite = new javax.swing.JLabel();
        pnlNews1 = new vue.PnlNews();
        pnlNews2 = new vue.PnlNews();
        pnlNews3 = new vue.PnlNews();

        setBackground(new java.awt.Color(255, 0, 0));
        setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        setLayout(null);

        lblNomSite.setBackground(new java.awt.Color(255, 255, 255));
        add(lblNomSite);
        lblNomSite.setBounds(20, 10, 240, 20);
        add(pnlNews1);
        pnlNews1.setBounds(10, 50, 190, 130);
        add(pnlNews2);
        pnlNews2.setBounds(210, 50, 220, 130);
        add(pnlNews3);
        pnlNews3.setBounds(440, 50, 220, 130);
    }// </editor-fold>//GEN-END:initComponents

    public JLabel getLblNomSite() {
        return lblNomSite;
    }

    public PnlNews getPnlNews1() {
        return pnlNews1;
    }

    public PnlNews getPnlNews2() {
        return pnlNews2;
    }

    public PnlNews getPnlNews3() {
        return pnlNews3;
    }

    public void setLblNomSite(JLabel lblNomSite) {
        this.lblNomSite = lblNomSite;
    }

    public void setPnlNews1(PnlNews pnlNews1) {
        this.pnlNews1 = pnlNews1;
    }

    public void setPnlNews2(PnlNews pnlNews2) {
        this.pnlNews2 = pnlNews2;
    }

    public void setPnlNews3(PnlNews pnlNews3) {
        this.pnlNews3 = pnlNews3;
    }

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblNomSite;
    private vue.PnlNews pnlNews1;
    private vue.PnlNews pnlNews2;
    private vue.PnlNews pnlNews3;
    // End of variables declaration//GEN-END:variables
}
