/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vue;

/**
 *
 * @author Esteban
 */
public class PnlSupprimerSite extends javax.swing.JPanel {

    /**
     * Creates new form PnlSupprimerSite
     */
    public PnlSupprimerSite() {
        initComponents();
        this.setBounds(0, 0, 240, 250);
        placeComposant();
    }
    
    public final void placeComposant(){
        lblSupprimerSite.setBounds(0, this.getHeight()/6, this.getWidth(), this.getHeight()/6);
        lblCategorie.setBounds(this.getWidth()/4, this.getHeight()/6+this.getHeight()/6+10, this.getWidth()/3, this.getHeight()/6);
        lblSite.setBounds(this.getWidth()/4, this.getHeight()/6+2*this.getHeight()/6+20, this.getWidth()/3, this.getHeight()/6);
        cmbBoxCategorie.setBounds(3*this.getWidth()/4, this.getHeight()/6+this.getHeight()/6+10, 4*this.getWidth()/5, this.getHeight()/7);
        cmbBoxSite.setBounds(3*this.getWidth()/4, this.getHeight()/6+2*this.getHeight()/6+20, 4*this.getWidth()/5, this.getHeight()/7);
        btnSupprimer.setBounds(this.getWidth()/3, this.getHeight()/6+3*this.getHeight()/6+30, 4*this.getWidth()/5, this.getHeight()/7);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblCategorie = new javax.swing.JLabel();
        cmbBoxCategorie = new javax.swing.JComboBox();
        lblSite = new javax.swing.JLabel();
        cmbBoxSite = new javax.swing.JComboBox();
        btnSupprimer = new javax.swing.JButton();
        lblSupprimerSite = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createEtchedBorder());
        setLayout(null);

        lblCategorie.setText("Catégorie");
        add(lblCategorie);
        lblCategorie.setBounds(40, 40, 92, 28);

        cmbBoxCategorie.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(cmbBoxCategorie);
        cmbBoxCategorie.setBounds(190, 40, 130, 20);

        lblSite.setText("Site");
        add(lblSite);
        lblSite.setBounds(40, 100, 90, 30);

        cmbBoxSite.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(cmbBoxSite);
        cmbBoxSite.setBounds(190, 100, 130, 20);

        btnSupprimer.setText("Supprimer");
        add(btnSupprimer);
        btnSupprimer.setBounds(140, 170, 100, 23);

        lblSupprimerSite.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSupprimerSite.setText("Supprimer un site");
        add(lblSupprimerSite);
        lblSupprimerSite.setBounds(120, 10, 150, 20);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSupprimer;
    private javax.swing.JComboBox cmbBoxCategorie;
    private javax.swing.JComboBox cmbBoxSite;
    private javax.swing.JLabel lblCategorie;
    private javax.swing.JLabel lblSite;
    private javax.swing.JLabel lblSupprimerSite;
    // End of variables declaration//GEN-END:variables
}
